export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <section className="max-w-5xl mx-auto px-6 py-24">
        <div className="inline-flex items-center rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-2 text-cyan-300 text-sm mb-8">
          Terms & Conditions
        </div>

        <h1 className="text-5xl md:text-6xl font-bold leading-tight mb-10">
          Terms & Conditions
          <span className="block text-cyan-400 mt-2">CompareCSV</span>
        </h1>

        <p className="text-slate-300 text-lg leading-8">
          Last updated: May 2026
        </p>
      </section>

      <section className="max-w-5xl mx-auto px-6 pb-32">
        <div className="rounded-[32px] border border-white/10 bg-white/5 p-10 md:p-14">
          <div className="space-y-12 text-slate-300 text-lg leading-8">
            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using CompareCSV, you agree to these Terms &
                Conditions. If you do not agree, please do not use the website.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                2. About CompareCSV
              </h2>
              <p>
                CompareCSV is an AI-powered spreadsheet analysis platform that
                helps users upload, compare, merge, analyze, and generate
                insights from CSV and Excel files.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                3. Use of the Service
              </h2>
              <p>You agree to use CompareCSV only for lawful purposes.</p>
              <ul className="list-disc pl-6 mt-6 space-y-3">
                <li>Do not upload illegal, harmful, or abusive content.</li>
                <li>Do not attempt to disrupt or misuse the platform.</li>
                <li>Do not use the service for fraudulent activities.</li>
                <li>Do not reverse engineer or attack the website.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                4. Uploaded Files
              </h2>
              <p>
                Users are responsible for the data they upload. You should avoid
                uploading sensitive, confidential, financial, medical, legal, or
                personally identifiable information unless you are authorized to
                do so.
              </p>
              <p className="mt-4">
                CompareCSV processes uploaded files to provide analysis,
                comparison, charting, and AI-generated outputs.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                5. AI-Generated Output
              </h2>
              <p>
                CompareCSV may generate insights, summaries, reports, blog
                content, YouTube talking points, and other AI-assisted outputs.
                AI-generated content may contain errors or incomplete
                interpretations.
              </p>
              <p className="mt-4">
                You are responsible for reviewing and verifying all AI-generated
                outputs before relying on or publishing them.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                6. No Professional Advice
              </h2>
              <p>
                CompareCSV does not provide legal, financial, medical, tax,
                investment, accounting, or professional advice. Any output
                generated by the platform is for informational and productivity
                purposes only.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                7. Accuracy & Availability
              </h2>
              <p>
                We aim to provide reliable tools, but we do not guarantee that
                the service will always be error-free, uninterrupted, accurate,
                or available at all times.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                8. Intellectual Property
              </h2>
              <p>
                The CompareCSV website, design, branding, code, content, and
                features are owned by CompareCSV or its respective licensors.
                You may not copy, reproduce, or redistribute platform materials
                without permission.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                9. Third-Party Services
              </h2>
              <p>
                CompareCSV may use third-party services for hosting, analytics,
                AI processing, email delivery, and advertising. These services
                may operate under their own terms and privacy policies.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                10. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by law, CompareCSV is not liable
                for indirect, incidental, consequential, special, or financial
                losses arising from your use of the website or generated
                outputs.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                11. Changes to These Terms
              </h2>
              <p>
                We may update these Terms & Conditions from time to time. Any
                changes will be posted on this page with an updated revision
                date.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-white mb-6">
                12. Contact
              </h2>
              <p>
                For questions about these Terms & Conditions, contact us at:
              </p>

              <div className="rounded-2xl bg-black/30 border border-white/10 p-5 mt-6 text-cyan-300 break-all">
                support@comparecsv.org
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}