import jsPDF from "jspdf";

type ExportPDFProps = {
  title: string;
  mode: string;
  aiResult: string;
  totalRows?: number;
  totalColumns?: number;
  missingValues?: number;
  duplicateCount?: number;
};

export function exportAIReportPDF({
  title,
  mode,
  aiResult,
  totalRows,
  totalColumns,
  missingValues,
  duplicateCount,
}: ExportPDFProps) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;

  let y = 20;

  doc.setFontSize(20);
  doc.text(title, margin, y);

  y += 10;

  doc.setFontSize(11);
  doc.text("Generated by CompareCSV - AI Data Storytelling Platform", margin, y);

  y += 12;

  doc.setFontSize(14);
  doc.text("Report Summary", margin, y);

  y += 8;

  doc.setFontSize(11);

  const stats = [
    `Mode: ${mode}`,
    `Total Rows: ${totalRows ?? "-"}`,
    `Total Columns: ${totalColumns ?? "-"}`,
    `Missing Values: ${missingValues ?? "-"}`,
    `Duplicate Rows: ${duplicateCount ?? "-"}`,
  ];

  stats.forEach((item) => {
    doc.text(item, margin, y);
    y += 7;
  });

  y += 8;

  doc.setFontSize(14);
  doc.text("AI Generated Analysis", margin, y);

  y += 8;

  doc.setFontSize(11);

  const lines = doc.splitTextToSize(aiResult || "No AI result available.", maxWidth);

  lines.forEach((line: string) => {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }

    doc.text(line, margin, y);
    y += 7;
  });

  doc.save("comparecsv-ai-report.pdf");
}