import jsPDF from "jspdf";

type ExportPDFProps = {
  title: string;
  mode: string;
  aiResult: string;
  totalRows?: number;
  totalColumns?: number;
  missingValues?: number;
  duplicateCount?: number;
};

export function exportAIReportPDF({
  title,
  mode,
  aiResult,
  totalRows,
  totalColumns,
  missingValues,
  duplicateCount,
}: ExportPDFProps) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  const margin = 15;

  const maxWidth = pageWidth - margin * 2;

  let y = 20;

  // Title
  doc.setFontSize(20);

  doc.text(title, margin, y);

  y += 10;

  // Subtitle
  doc.setFontSize(11);

  doc.text(
    "Generated by CompareCSV - AI Data Storytelling Platform",
    margin,
    y
  );

  y += 14;

  // Summary Heading
  doc.setFontSize(15);

  doc.text("Dataset Summary", margin, y);

  y += 10;

  // Summary Content
  doc.setFontSize(11);

  const summaryLines = [
    `Mode: ${mode}`,
    `Total Rows: ${totalRows ?? "-"}`,
    `Total Columns: ${totalColumns ?? "-"}`,
    `Missing Values: ${missingValues ?? "-"}`,
    `Duplicate Rows: ${duplicateCount ?? "-"}`,
  ];

  summaryLines.forEach((line) => {
    doc.text(line, margin, y);

    y += 7;
  });

  y += 10;

  // AI Section
  doc.setFontSize(15);

  doc.text("AI Generated Insights", margin, y);

  y += 10;

  doc.setFontSize(11);

  const aiLines = doc.splitTextToSize(
    aiResult || "No AI analysis available.",
    maxWidth
  );

  aiLines.forEach((line: string) => {
    if (y > 280) {
      doc.addPage();

      y = 20;
    }

    doc.text(line, margin, y);

    y += 7;
  });

  // Save
  doc.save("comparecsv-ai-report.pdf");
}